export const routes = {
  home: '/',
  card: '/debit-card',
  order: '/debit-card/order',
  wallet: '/wallet',
  crypto: '/crypto',
  loan: '/loan',
  about: '/about',
  partnership: '/partnership',
  contact: '/contact',
  terms: '/terms',
  security: '/terms/security',
  rules: '/terms/rules',
  policy: '/terms/policy',
  confidentiality: '/terms/privacy-policy',
  agreement: '/terms/agreement',
}
