export const routes = {
  home: '/',
  card: '/debit-card',
  order: '/debit-card/order',
  wallet: '/wallet',
  crypto: '/crypto',
  loan: '/loan',
  about: '/about',
  partnership: '/partnership',
  contact: '/contact',
  terms: '/terms',
  security: '/system_usage',
  rules: '/rules',
  policy: '/usage_policy',
  confidentiality: '/confidentiality',
  agreement: '/service_agreement',
}
